# Dependencies
markdown:        kramdown
highlighter:      rouge

syntax-highlighting:
  enabled : true
  css: syntax.css

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            Vikram Kumar Srirangam
url:              http://vwtt.github.io
baseurl:          /

author:
  name:           'Vikram Kumar Srirangam'
  url:            https://twitter.com/vwtt

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/vwtt/vwtt.github.io
