# Dependencies
markdown:        kramdown
highlighter:      rouge

syntax-highlighting:
  enabled : true
  css: syntax.css

# Custom Pages
include: ['_pages']

# Permalinks
permalink:        /blog/:title

# Setup
title:            Vikram Kumar Srirangam
url:              https://srirangamv.github.io
baseurl:          /

author:
  name:           'Vikram Kumar Srirangam'
  url:            https://twitter.com/srirangamv

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/srirangamv/srirangamv.github.io
